### PR TITLE
Added trackBy function to prevent destroy/init

### PR DESCRIPTION
**Pull request by celikceviren**
[JIRA Task](https://jira.cru.org/browse/GT-754)

- There are 3 components (resources, resource, and translation) used for building the translations page. 
- The resources component is the root component. It loads all the resources from the API and creates a resource component for each resource item received.
- The resource component is the root of translation components.  A resource component instance creates a translation component for each of the language items inside the resource item that the instance is built for.

After any change at the resources component or at a resource component or at a language component, the root component's (resources component) method for refreshing the resource data is triggered. 

When the resource data is refreshed, the source data array that generates the resource components is also altered and the resource components that were built for the previous version of the resource data array is destroyed and rebuilt. Therefore, the UI elements are removed from the web view and re-rendered with the new data even if most of the resource items in the source data array is not changed.

To prevent this behavior, I added a "trackBy" function to the ngFor loop that generates the resource components. This function prevents the components to be removed and re-added whenever the data that the component is built for is not removed from the source array.

Even if a resource component is not removed and re-added, the component can still get the updated version of the resource data that the component is built for.

You can test this by logging in to the app from 2 different browsers:

- Step 1: Edit a resource item's (eg. Emoji Survey) name from browser 1
- Step 2: Edit another resource item's (eg. Free From Fear) name from browser 2
- Step 3: When the resource is updated at browser 2, all resources will be reloaded, the UI will not be refreshed but you'll see the updated name for Emoji Survey resource.

### CODE REVIEW

**Comment by wrandall22** [comment]
@celikceviren can you rebase master to get the Travis change there so it will not fail the Travis build?

**Comment by wrandall22** [comment]
It doesn't look like you pulled down the latest master first.

**Comment by celikceviren** [comment]
I think it's ok now.

**Comment by wrandall22** [comment]
Do you think you could rebase all this into one commit? It's a bit noisy for git history. Not sure how familiar you are with rebasing.

**Comment by celikceviren** [comment]
I can create a new branch and apply this fix, then create a new PR and we delete this current PR. Will that work?

**Comment by wrandall22** [comment]
If you'd like. For your own growth, I suggest learning rebase. It's super helpful in development.

**Comment by celikceviren** [comment]
@wrandall22 : I tried to that, I picked my first commit, tried to squash the others and rebase and then push. I think it was ok but the history kept all my commits and they're not removed. So I think it did not work. Anyway, I created a new branch and pushed a single commit.

**Comment by wrandall22** [comment]
Closed in favor of #144

**Pull request closed without merging**
