### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by OzzieOrca** [comment]
What's the reason for disabling Chrome's sandbox?

**Comment by OzzieOrca** [comment]
I see the errors now. Guess I've usually run PhantomJS on Travis instead of Chrome.

**Comment by frett** [comment]
Yup, caused by a Travis change to mitigate the Meltdown bug. I can switch to PhantomJS if you'd prefer, just need a reference to documentation on how to configure it

**Comment by OzzieOrca** [comment]
Hmm, interesting. It should just be installing https://github.com/karma-runner/karma-phantomjs-launcher (`yarn add -D karma-phantomjs-launcher`) and changing the `browsers` array to just be `['PhantomJS']`. It may not be that easy though...

One thing is that if the JS isn't compiled before running on PhantomJS, it will throw errors if any ES6 features are used. It's pretty far behind the current JS specs. I'm not even sure if it has a native promise implementation. Hopefully that `@angular/cli/plugins/karma` plugin configures it correctly.

**Comment by frett** [comment]
running into the JS not being compiled, I'll just stick with Chrome for tests since that is currently working.

**Pull request merged**
